language: go

sudo: false

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp -f test/config_travis.toml test/config_test.toml

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

env:
  - TRAVIS_NODE_VERSION="0.12"

install:
  # from http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - make install

script:
  - make test
