language: go

sudo: false

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp -f test/config_travis.toml test/config_test.toml

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - make install

script:
  - make test
